rewolucja/rewolucja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import TemplateView

from website.sitemaps import Static_Sitemap, Post_Sitemap, Product_Sitemap

sitemaps = {
    'static': Static_Sitemap(),
    'post': Post_Sitemap(),
    'product': Product_Sitemap(),
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('summernote/', include('django_summernote.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path("robots.txt",TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rewolucja/website/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views

app_name = 'website'

urlpatterns = [
    #index
    path('', views.index, name='index'),
    #post_detail
    path('blog/<slug:slug>/', views.post_detail, name="post_detail"),
    #store
    path('sklep/', views.store, name="store"),
    #product detail
    path('sklep/<slug:slug>/', views.product_detail, name="product_detail"),
    #art
    path('sztuka/', views.art, name="art"),
    #search by tag
    path('tag/<slug:slug>', views.view_by_tag, name="view_by_tag"),
    path('o-nas/', views.about, name="about"),
    #newsletter
    path('newsletter/', views.newsletter_signup, name='newsletter'),
    path("newsletter/unsubscribe/<int:conf_num>/", views.unsubscribe_newsletter, name='unsubscribe_newsletter')

]

rewolucja/website/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.urls import reverse
from django.utils.text import slugify
from django.core.validators import RegexValidator
from taggit.managers import TaggableManager
from image_cropping import ImageRatioField
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
from django_countries.fields import CountryField


# Blog models
class Post(models.Model):
    STATUS_CHOICE = (
        ('draft','Wstrzymaj'),
        ('published', 'Opublikuj')
    )
    title = models.TextField(null=False, verbose_name="Tytuł")
    subtitle = models.TextField(null=True, blank=True, verbose_name="Podtytuł(Opcjonalnie)")
    text = models.TextField(verbose_name="Treść Posta")
    image = models.ImageField(upload_to ='uploads/articles/thumbnails', null=False, verbose_name="Zdjęcie")
    post_thumbnail = ImageRatioField('image', '900x450', size_warning=True, verbose_name="Miniaturka 800x300")
    tags = TaggableManager(verbose_name="tagi")
    status = models.CharField(max_length=100, choices=STATUS_CHOICE, verbose_name="Status publikacji", default="draft")
    slug = models.SlugField(max_length=250, unique=True, null=False)
    hits = models.IntegerField(default=0, editable=False, verbose_name="Wyświetlenia")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Data utworzenia")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Data aktualizacji")

    class Meta:
        ordering = ['-created_at', 'updated_at']
        verbose_name = "Post"
        verbose_name_plural = "Posty"

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('website:post_detail', args=[self.slug])

    def send_newsletter(self):
        pass

#art model
class ArtItem(models.Model):
    title = models.TextField(null=False, verbose_name="Tytuł")
    description = models.TextField(null=True, blank=True, verbose_name="Opis(Opcjonalnie")
    author = models.CharField(max_length=256, blank=True, null=True)
    image = models.ImageField(upload_to ='uploads/art/images', null=False, verbose_name="Zdjęcie")
    visible = models.BooleanField(default=True, verbose_name="Wyświetlaj")
    tags = TaggableManager(verbose_name="tagi")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Data utworzenia")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Data aktualizacji")

    class Meta:
        ordering = ['-created_at', 'updated_at']
        verbose_name = "Sztuka"
        verbose_name_plural = "Sztuka"

    def __str__(self):
        return self.title


# Store models
class ProductCategory(models.Model):
    name = models.TextField(blank=True, null=False, verbose_name="Nazwa Kategorii/Kolekcji")
    description = models.TextField(blank=True, null=True, verbose_name="Opis(Opcjonalnie)")
    slug = models.SlugField(max_length=150, unique=True, blank=True, null=False)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Data utworzenia")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Data aktualizacji")

    class Meta:
        ordering = ('name', 'created_at')
        verbose_name = "Kategoria Produktu"
        verbose_name_plural = "Kategorie Produktów"

    def  __str__(self):
        return self.name

class Product(models.Model):
    category = models.ForeignKey(ProductCategory, related_name='category', on_delete=models.PROTECT, verbose_name="Kategoria")
    name = models.TextField(blank=True, null=False, verbose_name="Nazwa")
    description = models.TextField(blank=True, null=False, verbose_name="Opis")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Cena")
    available = models.BooleanField(default=True, verbose_name="Dostępność")
    stock = models.PositiveIntegerField(verbose_name="Ilość")
    slug = models.SlugField(max_length=250, unique=True, null=False)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Data utworzenia")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Data aktualizacji")

    class Meta:
        ordering = ('created_at',)
        verbose_name="Produkt"
        verbose_name_plural="Produkty"

    def __str__(self):
        return self.name
    
    def check_if_sold_out(self):
        if self.stock == 0:
            self.available = False

    def get_absolute_url(self):
        return reverse('website:product_detail', args=[self.slug])

class ProductOptions(models.Model):
    SIZE_OPTIONS = [
        ("S", "S"),
        ("M", "M"),
        ("L", "L"),
        ("XL", "XL"),
        ("XXL", "XXL"),
        ("NO SIZE", "Brak rozmiaru"),
        ("universal", "Uniwersalny"),
    ]

    product = models.ForeignKey(Product, related_name="options", on_delete=models.CASCADE, verbose_name="Produkt")
    product_size = models.CharField(max_length=100, choices=SIZE_OPTIONS, verbose_name="Rozmiar produktu")
    stock = models.PositiveIntegerField()
    sold_out = models.BooleanField(default=False, verbose_name="Wyprzedane")

    class Meta:
        verbose_name = "Opcje produktu"
        verbose_name_plural = "Opcje produktów"

    def check_if_sold_out(self):
        if self.stock == 0:
            self.sold_out = True
            
class ProductImage(models.Model):
    product = models.ForeignKey(Product, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField()
    main_image = models.BooleanField(default=False, verbose_name="Główne zdjęcie")

    class Meta:
        verbose_name = "Zdjęcie produktu"
        verbose_name_plural = "Zdjęcia produktów"

class Order(models.Model):
    first_name = models.CharField(max_length=200, blank=True, null=False, verbose_name="Imie")
    last_name = models.CharField(max_length=200, blank=True, null=False, verbose_name="Nazwisko")
    email = models.EmailField(blank=True, null=False)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Dozwolony format numeru telefonu: '+999999999'. Do 15 cyfr.")
    phone = models.CharField(validators=[phone_regex], max_length=17, blank=True, null=False, verbose_name="Numer Telefonu")
    address_line_1 = models.CharField(max_length=200, blank=True, null=False, verbose_name="Adres linia 1")
    address_line_2 = models.CharField(max_length=200, blank=True, null=True, verbose_name="Adres linia 2")
    city = models.CharField(max_length=100,blank=True, null=False, verbose_name="Miasto")
    zip_code = models.CharField(max_length=30, blank=True, null=False, verbose_name="Kod pocztowy")
    country = CountryField(verbose_name="Kraj")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Data utworzenia")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Data aktualizacji")
    sent = models.BooleanField(default=False, verbose_name="Wysłane")
    paid = models.BooleanField(default=False, verbose_name="Zapłacone")

    class Meta:
        ordering = ('created_at',)
        verbose_name = "Zamówienie"
        verbose_name_plural = "Zamówienia"

    def __str__(self):
        return "Zamówienie {}".format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name="items", on_delete=models.CASCADE, verbose_name="Zamówienie")
    product = models.ForeignKey(Product, related_name="order_items", on_delete=models.CASCADE, verbose_name="Produkt")
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.id

    def get_cost(self):
        return self.price * self.quantity

# Newsletter models
class Subscriber(models.Model):
    email = models.EmailField(unique=True, null=False)
    conf_num = models.CharField(max_length=15)
    confirmed = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Subskrybent"
        verbose_name_plural = "Subskrybenci"

    def __str__(self):
        return self.email

    def send_welcome_email(self):
        if self.confirmed == False:
            message = Mail(from_email=settings.FROM_EMAIL_NEWSLETTER, to_emails=self.email, subject="Witaj w newsletterze rewolucja.pl", 
            html_content="""
                        <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
                        <html xmlns="http://www.w3.org/1999/xhtml" lang="pl-PL">
                        <head>
                            <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
                            <title>Newsletter Rewolucja Studio</title>
                            <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
                        </head>
                        <body>
                            <h1>TEST</h1>
                        </body
                        </html>
                        """)

            sg = SendGridAPIClient(settings.SENDGRID_API_KEY)
            response = sg.send(message)
            print(response)
            self.confirmed = True

    def get_unsubscribe_url(self):
        return reverse('website:unsubscribe_newsletter', args=[self.conf_num])

class Newsletter(models.Model):
    title = models.TextField(blank=True, null=False, verbose_name="Tytuł")
    content = models.FileField(upload_to='uploads/newsletters', verbose_name="Zawartość (Plik HTML)")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Data utworzenia")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Data aktualizacji")

    class Meta:
        ordering = ('created_at', 'title')
        verbose_name = "Newsletter"
        verbose_name_plural = "Newslettery"

    def __str__(self):
        return self.title + " " + self.created_at.strftime("%B %d, %Y")

rewolucja/website/forms.py
from django import forms
from website.models import Order

class NewSubscriberForm(forms.Form):
    email = forms.EmailField(label='Your email', max_length=100, widget=forms.EmailInput(attrs={'class': 'form-control'}))

class OrderForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(OrderForm, self).__init__(*args, **kwargs)

        self.fields['first_name'].required = True
        self.fields['last_name'].required = True
        self.fields['email'].required = True
        self.fields['phone'].required = True
        self.fields['address_line_1'].required = True
        self.fields['address_line_2'].required = False
        self.fields['sip_code'].required = True
        self.fields['city'].required = True
        self.fields['country'].required = True
    
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'phone', 'address_line_1', 'address_line_2', 'zip_code', 'city','country']

rewolucja/website/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.csrf import csrf_exempt
from django.core.mail import EmailMessage
from taggit.models import Tag
from .cart import Cart
import random

from .models import Post, Subscriber, ArtItem, Product, ProductCategory, ProductOptions, ProductImage

#helpers
def random_digits():
    return "%0.12d" % random.randint(0, 999999999999)

def index(request):
    all_posts = Post.objects.filter(status="published").order_by('-created_at')
    main_post = all_posts[0]
    featured_posts = all_posts[1:4]

    post_list = all_posts

    page = request.GET.get('page', 1)
    paginator = Paginator(post_list, 2)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'main_post': main_post,
        'featured_posts': featured_posts,
        'posts': posts
    }
    return render(request, 'website/index.html', context)

def post_detail(request, slug):
    post = get_object_or_404(Post, slug=slug)

    #increment hits counter
    post.hits += 1
    post.save()

    context = {
        'post': post
    }

    return render(request, 'website/post_detail.html', context)

def view_by_tag(request, slug):
    tag = Tag.objects.filter(slug=slug).values_list('name', flat=True)
    name = slug
    post_list = Post.objects.filter(tags__name__in=tag, status="published")

    page = request.GET.get('page', 1)
    paginator = Paginator(post_list, 3)
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {
        'name': name,
        'tag': tag,
        'posts': posts
    }

    return render(request, 'website/view_by_tag.html', context)

def art(request):
    art_items = ArtItem.objects.filter(visible=True).order_by('created_at')
    context = {
        'art_items': art_items
    }
    return render(request, 'website/art.html', context)

def store(request):
    products = Product.objects.filter(available=True)
    context = {
        'products': products
    }
    return render(request, 'website/store.html', context)

def order_create(request):
    pass

def send_order_confirmation(order):
    pass

def send_order_notification(order):
    pass

def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug)
    images  = product.images.all()
    options = product.options.all()
    context = {
        'product': product,
        'images': images,
        'options': options
    }
    return render(request, 'website/product_detail', context)

def about(request):
    context = {}
    return render(request, 'website/about.html', context)

def search(request):
    pass

@csrf_exempt
def newsletter_signup(request):
    if request.method == "POST":
        new_email = request.POST.get('email')
        if Subscriber.objects.filter(email=new_email).exists():
            subscriber = Subscriber.objects.filter(email=new_email)
            if not subscriber.confirmed:
                subscriber.confirmed = True
                subscriber.save()
                return
            else:
                return
        else:
            new_subscriber = Subscriber(email=new_email, conf_num=random_digits())
            new_subscriber.save()
            new_subscriber.send_welcome_email()
        return render(request, 'website/newsletter.html')

@csrf_exempt
def unsubscribe_newsletter(request, conf_num):
    #find subscriber with given conf num
    subscriber = get_object_or_404(Subscriber, conf_num)
    subscriber.confirmed = False
    subscriber.save()
    return render(request, 'website/unsubscribe.html')

rewolucja/website/templates/website/about.html
{% extends 'base.html' %}
{% load static %}
{% block css_files %}
    <link rel="stylesheet" href="{% static 'css/about_styles.css' %}">
{% endblock %}
{% block content %}
<div class="container-fluid">
    
</div>
{% endblock %}

rewolucja/website/templates/website/art.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Sztuka | REWOLUCJA{% endblock %}
{% block css_files %}
    <link rel="stylesheet" href="{% static 'css/art_styles.css' %}">
    <!--Lightbox css-->
    <link rel="stylesheet" href="{% static 'css/minified/lightbox.min.css' %}">
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="masonry-wrapper">
            <div class="masonry">
                {% for item in art_items %}
                <div class="masonry-item">
                    <a href="{{item.image.url}}" class="example-image-link" data-lightbox="example-1">
                        <img src="{{item.image.url}}" alt="" class="masonry-content" width="100%">
                    </a>
                </div>
                {% endfor %}
            </div>
        </div
    </div>
{% endblock %}
{% block bottom_body_js_block %}
    <!--Masonry-->
    <script src="{% static 'js/minified/masonry.pkgd.min.js' %}"></script>
    <script src="{% static 'js/minified/gallery.min.js' %}"></script>
    <!--Lightbox-->
    <script src="{% static 'js/minified/lightbox.min.js' %}"></script>
    <script>
        lightbox.option({
            'resizeDuration': 200,
            'wrapAround': true,
            'disableScrolling': true,
            'alwaysShowNavOnTouchDevices': true,
            'showImageNumberLabel': false,
            'albumLabel': "Zdjęcie %1 z %2"
        })
    </script>
{% endblock %}

rewolucja/website/templates/website/index.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block css_files %}
    <link rel="stylesheet" href="{% static 'css/index_styles.css' %}?version=2">
{% endblock %}
{% block content %}
    
    <!--Main post -->
    <div class="container-fluid" id="mainPost">
        <a href="{{ main_post.get_absolute_url }}">
            <div class="row align-items-center">
                    <div class="col-md-8">
                        <img src="{% thumbnail main_post.image 900x450 box=main_post.post_thumbnail crop detail %}" alt="" class="img-fluid">
                    </div>
                    <div class="col-md-4">
                        <div>
                            <h1 class="post-title-1">{{ main_post.title }}</h1>
                            <h3 class="post-subtitle">{{ main_post.subtitle }}</h3>
                        </div>
                    </div>
            </div>
        </a>
    </div>
    
    <!--Featured posts-->
    <div class="container-fluid" id="featuredPosts" style="padding-top: 40px;">
        <div class="row">
            {% for post in featured_posts %}
            <div class="col-md-4">
                <a href="{{ post.get_absolute_url }}">
                    <img src="{% thumbnail post.image 900x450 box=post.post_thumbnail crop detail %}" alt="" class="img-fluid">
                    <h1 class="post-title-2">{{post.title}}</h1>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

    <!-- Infinite container -->
    <div class="container-fluid">
        <div class="infinite-container">

            {% for post in posts %}
                <div class="infinite-item">
                    <div class="row">
                        <div class="col-md-4">
                            <img src="{% thumbnail post.image 900x450 box=post.post_thumbnail crop detail %}" alt="" class="img-fluid">
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        
        {% if posts.has_next %}
            <a class="infinite-more-link" href="?page={{ posts.next_page_number }}">More</a>
        {% endif %}
    </div>


{% endblock %}
{% block bottom_body_js_block%}
    <script src="{% static 'js/minified/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'js/minified/jquery.waypoints.min.js' %}"></script>
    <script src="{% static 'js/minified/infinite.min.js' %}"></script>
    <script>
        var infinite = new Waypoint.Infinite({
          element: $('.infinite-container')[0],
          onBeforePageLoad: function () {
            $('.loading').show();
          },
          onAfterPageLoad: function ($items) {
            $('.loading').hide();
          }
        });
    </script>
{% endblock %}

rewolucja/website/templates/website/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load thumbnail %}
{% block title %} {{post.title}} | Rewolucja {% endblock %}
{% block css_files %}
    <link rel="stylesheet" href="{% static 'css/post_detail_styles.css' %}?version=3">
{% endblock %}
{% block meta %}
    <!--Meta description-->
    <meta name="description" content="{{post.subtitle}}">
    <!--Twitter card-->
    <meta name="twitter:card" content="summary" />
    <meta property="og:url" content="https://rewolucja.pl{{article.get_absolute_url}}" />
    <meta property="og:title" content="{{post.title}}" />
    <meta property="og:description" content="{{post.subtitle}}" />
    <meta property="og:image" content="https://rewolucja.pl{{post.image.url}}" />

    <!--Facebook card-->
    <meta property="og:url" content="https://rewolucja.pl{{article.get_absolute_url}}" />
    <meta property="og:type" content="post" />
    <meta property="og:title" content="{{post.title}}" />
    <meta property="og:description" content="{{post.subtitle}}" />
    <meta property="og:image" content="https://rewolucja.pl{{post.image.url}}" />
{% endblock %}
{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-8">
                <!--Title-->
                <div class="row">
                    <h1>{{post.title}}</h1>
                </div>

                <!--Date-->
                <div class="row">
                    <p>{{post.created_at|date:'d-m-Y'}}</p>
                </div>

                <!--Tags-->
                <div class="row">
                    {% for tag in post.tags.all %} 
                    <a class="tag" href="{% url 'website:view_by_tag' tag.slug %}">
                        {{ tag.name }}
                    </a>
                    {% endfor %}
                </div>

                <!--Post image-->
                <div class="row" id="post-image">
                    <img src="{{post.image.url}}" alt="" class="img-fluid">
                </div>

                <!--Post text-->
                <div class="row" id="post-content">
                    {{post.text|safe}}    
                </div>
            </div>
            <!--Featured posts-->
            <div class="col-md-4">
            </div>
        </div>
    </div>
{% endblock %}

rewolucja/website/templates/website/product_detail.html
{% extends 'base.html' %}
{% load static %}

rewolucja/website/templates/website/store.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Sklep | REWOLUCJA{% endblock %}
{% block css_files %}
    <link rel="stylesheet" href="{% static 'css/store_styles.css' %}">
{% endblock %}
{% block content %}

{% endblock %}

rewolucja/website/templates/website/view_by_tag.html
{% extends 'base.html' %}
{% load static %}