rewolucja/rewolucja/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.contrib.sitemaps.views import sitemap
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import TemplateView

from website.sitemaps import Static_Sitemap, Post_Sitemap, Product_Sitemap

sitemaps = {
    'static': Static_Sitemap(),
    'post': Post_Sitemap(),
    'product': Product_Sitemap(),
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('summernote/', include('django_summernote.urls')),
    url(r'^sitemap\.xml$', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path("robots.txt",TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rewolucja/website/urls.py
from django.urls import path, include
from django.conf.urls import url
from . import views

app_name = 'website'

urlpatterns = [
    #index
    path('', views.index, name='index'),
    #post_detail
    path('blog/<slug:slug>/', views.post_detail, name="post_detail"),
    #store
    path('sklep/', views.store, name="store"),
    #product detail
    path('sklep/<slug:slug>/', views.product_detail, name="product_detail"),
    #art
    path('sztuka/', views.art, name="art"),
    #search by tag
    path('tag/<slug:slug>', views.view_by_tag, name="view_by_tag"),
    path('o-nas/', views.about, name="about"),
    #newsletter
    path('newsletter/', views.newsletter_signup, name='newsletter'),
    path("newsletter/unsubscribe/<int:conf_num>/", views.unsubscribe_newsletter, name='unsubscribe_newsletter')

]

rewolucja/templates/components/_cssfiles.html
{% load static %}
<!--Main styles-->
<link rel="stylesheet" href="{% static 'css/main_styles.css' %}">
<!--Navigation-->
<link rel="stylesheet" href="{% static 'css/navigation.css' %}">
<!--Footer-->
<link rel="stylesheet" href="{% static 'css/footer.css' %}">
<!--Bootstrap css-->
<link rel="stylesheet" href="{% static 'css/minified/bootstrap.min.css' %}">
<!--Fontawesome-->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.3.0/css/font-awesome.min.css">

rewolucja/templates/components/_footer.html
{% load static %}
<div class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4">
                <h1>COL1</h1>
            </div>
            <div class="col-md-4">
                <h1>COL2</h1>
            </div>
            <div class="col-md-4">
                <form class="input-group" method="POST" action="{% url 'website:newsletter' %}">
                    {% csrf_token %}
                    <input type="text" class="form-control form-control-sm" placeholder="Email"
                      aria-label="Email" aria-describedby="basic-addon2" name="email">
                    <div class="input-group-append">
                      <button class="btn btn-sm btn-outline-white my-0" type="button">Bądź na bierząco</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

rewolucja/templates/components/_metatags.html
{% load static %}
<link rel="apple-touch-icon" sizes="57x57" href="{% static 'img/icons/apple-icon-57x57.png' %}">
<link rel="apple-touch-icon" sizes="60x60" href="{% static 'img/icons/apple-icon-60x60.png' %}">
<link rel="apple-touch-icon" sizes="72x72" href="{% static 'img/icons/apple-icon-72x72.png' %}">
<link rel="apple-touch-icon" sizes="76x76" href="{% static 'img/icons/apple-icon-76x76.png' %}">
<link rel="apple-touch-icon" sizes="114x114" href="{% static 'img/icons/apple-icon-114x114.png' %}">
<link rel="apple-touch-icon" sizes="180x180" href="{% static 'img/icons/apple-icon-180x180.png' %}">
<link rel="icon" type="image/png" sizes="192x192"  href="{% static 'img/icons/android-icon-192x192.png' %}">
<link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/icons/favicon-32x32.png' %}">
<link rel="icon" type="image/png" sizes="96x96" href="{% static 'img/icons/favicon-96x96.png' %}">
<link rel="icon" type="image/png" sizes="16x16" href="{% static 'img/icons/favicon-16x16.png' %}">
<link rel="manifest" href="{% static 'img/icons/manifest.json' %}">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="{% static 'img/icons/ms-icon-144x144.png' %}">
<meta name="theme-color" content="#ffffff">

rewolucja/templates/components/_navigation.html
{% load static %}
<nav class="navbar fixed-top navbar-expand-lg navbar-light d-flex align-items-center" id="navigation-bar" style="background-color: white;">
    <a class="navbar-brand" href="{% url 'website:index' %}">
      <img src="{% static 'img/logomale.png' %}" alt="" class="img-fluid" width="50" height="50">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-between" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a href="{% url 'website:index' %}" class="nav-link">Publicystyka</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'website:art' %}">Sztuka</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'website:store' %}">Sklep</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'website:about' %}">O nas</a>
        </li>
      </ul>
    </div>
</nav>